export type ColorTypes = {
  bgc: string,
  elemsBgc: string,
  primeColor: string,
  darkPrime: string,
  lightPrime: string,
  textColor: string,
  hoverText: string,
  darkGray: string,
  gray: string,
  lightGray: string,
  placeholderColor: string,
  disabledBgc: string,
  red: string,
  green: string,
  blue: string,
}

export const colors = {
  bgc: '#f6f6f6',
  elemsBgc: '#fff',
  primeColor: '#526ed3',
  darkPrime: '#314692',
  lightPrime: '#717b9f',
  textColor: '#303030',
  hoverText: '#fff',
  darkGray: '#6d6f7a',
  gray: '#717171',
  lightGray: '#e3e3e3',
  placeholderColor: '#8c8c8c',
  disabledBgc: '#c1c6d3',
  red: '#dc2020',
  green: '#36ac82',
  blue: '#399efa',
}